"""Send one real ACE SMTP test email."""

from datetime import (
    datetime,
    timezone,
)
import smtplib
import sys

from backend.app.config import (
    get_settings,
)
from backend.app.notifications.email import (
    SmtpEmailConfig,
    SmtpEmailTransport,
)
from backend.app.notifications.types import (
    NotificationMessage,
)


def main() -> int:
    """Send a real SMTP delivery test."""

    settings = get_settings()

    username = (
        settings.smtp_username
    )

    password = (
        settings.smtp_password.get_secret_value()
        if settings.smtp_password
        is not None
        else None
    )

    from_email = (
        settings.smtp_from_email
        or username
    )

    recipient = (
        settings.notification_to_email
    )

    if not username:
        print(
            (
                "SMTP_USERNAME is not "
                "configured."
            ),
            file=sys.stderr,
        )

        return 2

    if not password:
        print(
            (
                "SMTP_PASSWORD is not "
                "configured."
            ),
            file=sys.stderr,
        )

        return 2

    if not from_email:
        print(
            (
                "SMTP_FROM_EMAIL is not "
                "configured."
            ),
            file=sys.stderr,
        )

        return 2

    if not recipient:
        print(
            (
                "NOTIFICATION_TO_EMAIL "
                "is not configured."
            ),
            file=sys.stderr,
        )

        return 2

    config = SmtpEmailConfig(
        host=settings.smtp_host,
        port=settings.smtp_port,
        username=username,
        password=password,
        from_email=from_email,
        use_starttls=(
            settings.smtp_use_starttls
        ),
        timeout_seconds=(
            settings.smtp_timeout_seconds
        ),
    )

    transport = SmtpEmailTransport(
        config
    )

    now = datetime.now(
        timezone.utc
    )

    message = NotificationMessage(
        subject=(
            "[ACE] Email delivery test"
        ),
        text_body=(
            "ACE EMAIL DELIVERY TEST\n"
            "\n"
            "SMTP delivery is working.\n"
            "\n"
            "This message was generated by "
            "the ACE notification transport.\n"
            "\n"
            "Sent at:\n"
            f"{now.isoformat()}\n"
            "\n"
            "No job alert was generated."
        ),
    )

    print(
        (
            "Sending ACE test email "
            f"to {recipient}..."
        )
    )

    try:
        transport.send(
            message,
            recipient=recipient,
        )

    except (
        smtplib.SMTPException,
        OSError,
        ValueError,
    ) as exc:
        print(
            (
                "ACE email delivery failed: "
                f"{exc}"
            ),
            file=sys.stderr,
        )

        return 1

    print(
        "ACE test email sent successfully."
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )